"""Add DocumentUpload table

Revision ID: 4ca50de56068
Revises: 98b2bce06164
Create Date: 2026-02-27 20:00:49.088081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca50de56068'
down_revision: Union[str, Sequence[str], None] = '98b2bce06164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_upload',
    sa.Column('upload_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen.citizen_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.drop_table('policy_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.scheme_id'], name=op.f('policy_document_scheme_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_document_pkey'))
    )
    op.drop_table('document_upload')
    # ### end Alembic commands ###
