"""Initial migration

Revision ID: 98b2bce06164
Revises: 
Create Date: 2026-02-27 18:04:04.331415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b2bce06164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('citizen_id', sa.String(length=50), nullable=False),
    sa.Column('aadhar_number', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('annual_income', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('citizen_id'),
    sa.UniqueConstraint('aadhar_number')
    )
    op.create_table('scheme',
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('income_limit', sa.Integer(), nullable=True),
    sa.Column('district_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=50), nullable=True),
    sa.Column('scheme_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen.citizen_id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.scheme_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('document_vault',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citizen_id', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('document_hash', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen.citizen_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_vault')
    op.drop_table('application')
    op.drop_table('scheme')
    op.drop_table('citizen')
    # ### end Alembic commands ###
